name: get_bootimg_from_payload.bin

on:
  watch:
    types: [started]
    
env:
  ROM_URL: https://bigota.d.miui.com/OS1.0.21.0.UNBCNXM/miui_SHENNONG_OS1.0.21.0.UNBCNXM_c72d682b7d_14.0.zip
  TZ: Asia/Shanghai

jobs:
  make:
    runs-on: ubuntu-latest

    steps:

    - name: install Python 3.7
      uses: actions/setup-python@v1
      with:
          python-version: 3.7
    - name: Initialization environment 
      run: |
        cd ~
        pip install bsdiff4
        python -m pip install protobuf

    - name: Clone the tools source code
      run: |
       cd ~
       git clone https://github.com/vm03/payload_dumper.git
       
  
    - name: Download the ROM
      run: |
       cd ~
       wget -O rom.zip $ROM_URL
   
    - name: unzip the ROM
      run: |
       cd ~
       unzip rom.zip -d payload_dumper
    
    - name: extract the payload.bin
      run: |
       cd ~
       cd payload_dumper
       python payload_dumper.py payload.bin
   

    
    - name: Upload the bootimg to WeTransfer
      run: |
        cd ~
        curl -sL https://git.io/file-transfer | sh
        ./transfer wet ~/payload_dumper/output/boot.img
